
package powerschool.rest.publicportal;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import powerschool.rest.vo.xsd.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublicPortalServiceJSONPortType", targetNamespace = "http://publicportal.rest.powerschool.pearson.com")
@XmlSeeAlso({
    powerschool.rest.model.xsd.ObjectFactory.class,
    powerschool.rest.publicportal.xsd.ObjectFactory.class,
    powerschool.rest.vo.xsd.ObjectFactory.class,
    powerschool.util.xsd.ObjectFactory.class
})
public interface PublicPortalServiceJSONPortType {


    /**
     * 
     * @param userSessionVO
     * @return
     *     returns com.pearson.powerschool.rest.vo.xsd.ResultsVO
     */
    @WebMethod(action = "urn:logout")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.LogoutResponse")
    public ResultsVO logout(
        @WebParam(name = "userSessionVO", targetNamespace = "")
        UserSessionVO userSessionVO);

    /**
     * 
     * @param userSessionVO
     * @param studentID
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "urn:getStudentPhoto")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentPhoto", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.GetStudentPhoto")
    @ResponseWrapper(localName = "getStudentPhotoResponse", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.GetStudentPhotoResponse")
    public byte[] getStudentPhoto(
        @WebParam(name = "userSessionVO", targetNamespace = "")
        UserSessionVO userSessionVO,
        @WebParam(name = "studentID", targetNamespace = "")
        Long studentID);

    /**
     * 
     * @param ns
     * @param userSessionVO
     * @return
     *     returns com.pearson.powerschool.rest.vo.xsd.ResultsVO
     */
    @WebMethod(action = "urn:storeNotificationSettings")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "storeNotificationSettings", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.StoreNotificationSettings")
    @ResponseWrapper(localName = "storeNotificationSettingsResponse", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.StoreNotificationSettingsResponse")
    public ResultsVO storeNotificationSettings(
        @WebParam(name = "userSessionVO", targetNamespace = "")
        UserSessionVO userSessionVO,
        @WebParam(name = "ns", targetNamespace = "")
        NotificationSettingsVO ns);

    /**
     * 
     * @param studentId
     * @param userSessionVO
     * @return
     *     returns com.pearson.powerschool.rest.vo.xsd.ResultsVO
     */
    @WebMethod(action = "urn:getAllCourseRequests")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCourseRequests", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.GetAllCourseRequests")
    @ResponseWrapper(localName = "getAllCourseRequestsResponse", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.GetAllCourseRequestsResponse")
    public ResultsVO getAllCourseRequests(
        @WebParam(name = "userSessionVO", targetNamespace = "")
        UserSessionVO userSessionVO,
        @WebParam(name = "studentId", targetNamespace = "")
        Long studentId);

    /**
     * 
     * @param username
     * @param password
     * @param userType
     * @return
     *     returns com.pearson.powerschool.rest.vo.xsd.ResultsVO
     */
    @WebMethod(action = "urn:login")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.LoginResponse")
    public ResultsVO login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "userType", targetNamespace = "")
        Integer userType);

    /**
     * 
     * @param qil
     * @param userSessionVO
     * @param studentIDs
     * @return
     *     returns com.pearson.powerschool.rest.vo.xsd.ResultsVO
     */
    @WebMethod(action = "urn:getStudentData")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentData", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.GetStudentData")
    @ResponseWrapper(localName = "getStudentDataResponse", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.GetStudentDataResponse")
    public ResultsVO getStudentData(
        @WebParam(name = "userSessionVO", targetNamespace = "")
        UserSessionVO userSessionVO,
        @WebParam(name = "studentIDs", targetNamespace = "")
        List<Long> studentIDs,
        @WebParam(name = "qil", targetNamespace = "")
        QueryIncludeListVO qil);

    /**
     * 
     * @param courseRequestGroups
     * @param studentId
     * @param userSessionVO
     * @return
     *     returns com.pearson.powerschool.rest.vo.xsd.ResultsVO
     */
    @WebMethod(action = "urn:storeCourseRequests")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "storeCourseRequests", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.StoreCourseRequests")
    @ResponseWrapper(localName = "storeCourseRequestsResponse", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.StoreCourseRequestsResponse")
    public ResultsVO storeCourseRequests(
        @WebParam(name = "userSessionVO", targetNamespace = "")
        UserSessionVO userSessionVO,
        @WebParam(name = "studentId", targetNamespace = "")
        Long studentId,
        @WebParam(name = "courseRequestGroups", targetNamespace = "")
        List<CourseRequestGroupVO> courseRequestGroups);

    /**
     * 
     * @param userSessionVO
     * @param schoolNumber
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "urn:getSchoolMapBySchoolNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSchoolMapBySchoolNumber", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.GetSchoolMapBySchoolNumber")
    @ResponseWrapper(localName = "getSchoolMapBySchoolNumberResponse", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.GetSchoolMapBySchoolNumberResponse")
    public byte[] getSchoolMapBySchoolNumber(
        @WebParam(name = "userSessionVO", targetNamespace = "")
        UserSessionVO userSessionVO,
        @WebParam(name = "schoolNumber", targetNamespace = "")
        Long schoolNumber);

    /**
     * 
     * @param userSessionVO
     * @param studentIDs
     * @param month
     * @param year
     * @return
     *     returns com.pearson.powerschool.rest.vo.xsd.ResultsVO
     */
    @WebMethod(action = "urn:getStartStopTimeForAllSections")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStartStopTimeForAllSections", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.GetStartStopTimeForAllSections")
    @ResponseWrapper(localName = "getStartStopTimeForAllSectionsResponse", targetNamespace = "http://publicportal.rest.powerschool.pearson.com/xsd", className = "com.pearson.powerschool.rest.publicportal.xsd.GetStartStopTimeForAllSectionsResponse")
    public ResultsVO getStartStopTimeForAllSections(
        @WebParam(name = "userSessionVO", targetNamespace = "")
        UserSessionVO userSessionVO,
        @WebParam(name = "studentIDs", targetNamespace = "")
        List<Long> studentIDs,
        @WebParam(name = "month", targetNamespace = "")
        Integer month,
        @WebParam(name = "year", targetNamespace = "")
        Integer year);

}
