
package powerschool.rest.publicportal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublicPortalServiceJSON", targetNamespace = "http://publicportal.rest.powerschool.pearson.com", wsdlLocation = "https://ps01.bergen.org/pearson-rest/services/PublicPortalServiceJSON?wsdl")
public class PublicPortalServiceJSON
    extends Service
{

    private final static URL PUBLICPORTALSERVICEJSON_WSDL_LOCATION;
    private final static WebServiceException PUBLICPORTALSERVICEJSON_EXCEPTION;
    private final static QName PUBLICPORTALSERVICEJSON_QNAME = new QName("http://publicportal.rest.powerschool.pearson.com", "PublicPortalServiceJSON");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ps01.bergen.org/pearson-rest/services/PublicPortalServiceJSON?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICPORTALSERVICEJSON_WSDL_LOCATION = url;
        PUBLICPORTALSERVICEJSON_EXCEPTION = e;
    }

    public PublicPortalServiceJSON() {
        super(__getWsdlLocation(), PUBLICPORTALSERVICEJSON_QNAME);
    }

    public PublicPortalServiceJSON(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICPORTALSERVICEJSON_QNAME, features);
    }

    public PublicPortalServiceJSON(URL wsdlLocation) {
        super(wsdlLocation, PUBLICPORTALSERVICEJSON_QNAME);
    }

    public PublicPortalServiceJSON(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICPORTALSERVICEJSON_QNAME, features);
    }

    public PublicPortalServiceJSON(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicPortalServiceJSON(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicPortalServiceJSONPortType
     */
    @WebEndpoint(name = "PublicPortalServiceJSONHttpsSoap11Endpoint")
    public PublicPortalServiceJSONPortType getPublicPortalServiceJSONHttpsSoap11Endpoint() {
        return super.getPort(new QName("http://publicportal.rest.powerschool.pearson.com", "PublicPortalServiceJSONHttpsSoap11Endpoint"), PublicPortalServiceJSONPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicPortalServiceJSONPortType
     */
    @WebEndpoint(name = "PublicPortalServiceJSONHttpsSoap11Endpoint")
    public PublicPortalServiceJSONPortType getPublicPortalServiceJSONHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicportal.rest.powerschool.pearson.com", "PublicPortalServiceJSONHttpsSoap11Endpoint"), PublicPortalServiceJSONPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns PublicPortalServiceJSONPortType
     */
    @WebEndpoint(name = "PublicPortalServiceJSONHttpSoap11Endpoint")
    public PublicPortalServiceJSONPortType getPublicPortalServiceJSONHttpSoap11Endpoint() {
        return super.getPort(new QName("http://publicportal.rest.powerschool.pearson.com", "PublicPortalServiceJSONHttpSoap11Endpoint"), PublicPortalServiceJSONPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicPortalServiceJSONPortType
     */
    @WebEndpoint(name = "PublicPortalServiceJSONHttpSoap11Endpoint")
    public PublicPortalServiceJSONPortType getPublicPortalServiceJSONHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicportal.rest.powerschool.pearson.com", "PublicPortalServiceJSONHttpSoap11Endpoint"), PublicPortalServiceJSONPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns PublicPortalServiceJSONPortType
     */
    @WebEndpoint(name = "PublicPortalServiceJSONHttpSoap12Endpoint")
    public PublicPortalServiceJSONPortType getPublicPortalServiceJSONHttpSoap12Endpoint() {
        return super.getPort(new QName("http://publicportal.rest.powerschool.pearson.com", "PublicPortalServiceJSONHttpSoap12Endpoint"), PublicPortalServiceJSONPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicPortalServiceJSONPortType
     */
    @WebEndpoint(name = "PublicPortalServiceJSONHttpSoap12Endpoint")
    public PublicPortalServiceJSONPortType getPublicPortalServiceJSONHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicportal.rest.powerschool.pearson.com", "PublicPortalServiceJSONHttpSoap12Endpoint"), PublicPortalServiceJSONPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns PublicPortalServiceJSONPortType
     */
    @WebEndpoint(name = "PublicPortalServiceJSONHttpsSoap12Endpoint")
    public PublicPortalServiceJSONPortType getPublicPortalServiceJSONHttpsSoap12Endpoint() {
        return super.getPort(new QName("http://publicportal.rest.powerschool.pearson.com", "PublicPortalServiceJSONHttpsSoap12Endpoint"), PublicPortalServiceJSONPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicPortalServiceJSONPortType
     */
    @WebEndpoint(name = "PublicPortalServiceJSONHttpsSoap12Endpoint")
    public PublicPortalServiceJSONPortType getPublicPortalServiceJSONHttpsSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicportal.rest.powerschool.pearson.com", "PublicPortalServiceJSONHttpsSoap12Endpoint"), PublicPortalServiceJSONPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns PublicPortalServiceJSONPortType
     */
    @WebEndpoint(name = "PublicPortalServiceJSONHttpsEndpoint")
    public PublicPortalServiceJSONPortType getPublicPortalServiceJSONHttpsEndpoint() {
        return super.getPort(new QName("http://publicportal.rest.powerschool.pearson.com", "PublicPortalServiceJSONHttpsEndpoint"), PublicPortalServiceJSONPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicPortalServiceJSONPortType
     */
    @WebEndpoint(name = "PublicPortalServiceJSONHttpsEndpoint")
    public PublicPortalServiceJSONPortType getPublicPortalServiceJSONHttpsEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicportal.rest.powerschool.pearson.com", "PublicPortalServiceJSONHttpsEndpoint"), PublicPortalServiceJSONPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns PublicPortalServiceJSONPortType
     */
    @WebEndpoint(name = "PublicPortalServiceJSONHttpEndpoint")
    public PublicPortalServiceJSONPortType getPublicPortalServiceJSONHttpEndpoint() {
        return super.getPort(new QName("http://publicportal.rest.powerschool.pearson.com", "PublicPortalServiceJSONHttpEndpoint"), PublicPortalServiceJSONPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicPortalServiceJSONPortType
     */
    @WebEndpoint(name = "PublicPortalServiceJSONHttpEndpoint")
    public PublicPortalServiceJSONPortType getPublicPortalServiceJSONHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicportal.rest.powerschool.pearson.com", "PublicPortalServiceJSONHttpEndpoint"), PublicPortalServiceJSONPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICPORTALSERVICEJSON_EXCEPTION!= null) {
            throw PUBLICPORTALSERVICEJSON_EXCEPTION;
        }
        return PUBLICPORTALSERVICEJSON_WSDL_LOCATION;
    }

}
